name: Init Wiki
on: workflow_dispatch
jobs:
  init-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Init wiki
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euxo pipefail
          repo="${{ github.repository }}"
          tmp="$(mktemp -d)"
          cd "$tmp"
          git init -b main
          git config user.email "bot@reverberage.github.com"
          git config user.name "reverberage bot"
          echo "# n3rverberage" > Home.md
          echo "* [Home](Home)" > _Sidebar.md
          echo "" > _Footer.md
          git add .
          git commit -m "Initial wiki"
          git remote add origin "https://x-access-token:${GH_TOKEN}@github.com/${repo}.wiki.git"
          git push --set-upstream origin main 2>&1 || echo "EXIT: $?"
